package com.kainos.ea.enums;

public enum Capabilities {
    APPLIED_INNOVATION,
    BUSINESS_DEVELOPMENT_MARKETING,
    BUSINESS_SERVICES_SUPPORT,
    CYBER_SECURITY,
    DATA_AI,
    DELIVERY_MANAGEMENT,
    ENGINEERING,
    EXPERIENCE_DESIGN,
    PLATFORMS,
    PRE_SALES,
    PRODUCT_DIGITAL_ADVISORY,
    QUALITY_ASSURANCE;
}
